### ISSUE TITLE
Feedback on motivation and Intent behind the initiative

### ISSUE THREAD

**Issue by jurra** [delftopenhardware/openhardwarenl#1]
**How to follow up on this thread?**
- Please provide questions or comments, any support on the subject and also critical thinking would be very much appreciated.
- Any considerations or recommendations you have would be very much appreciated.

## Title: A White Paper on Open Hardware in the Netherlands: Guiding National and International Collaborations

**Introduction:**
This white paper aims to provide a comprehensive guideline for the implementation of open hardware initiatives in the Netherlands, particularly in academia. The paper will discuss how bottom-up initiatives at universities can be combined with top-down governance from organizations such as NWO to maximize the benefits of open hardware in science, education, and society. The goal of this paper is to provide a consistent narrative that showcases successful examples of open hardware from both national and international perspectives, and to advocate for an allocation of NWO funds towards open hardware projects.

**Considerations for an Open Hardware Program for the Netherlands:**
Open hardware has the potential to revolutionize science, education, and society by facilitating collaborative innovation and democratizing access to technology. It can enhance the reproducibility and transparency of research, as well as reduce costs and promote sustainable practices. By promoting open hardware initiatives, the Netherlands can position itself as a leader in open science and contribute to the global effort of achieving sustainable development goals. We also aim to touch upon which cases can benefit the most from open source practices applied to hardware, some cases are less likely to be implemented due to issues that come from economic constrains, competition, geopolitics, security, ethics, and so on.

**Implementation Plan:**
The white paper will be accompanied by a program document that explains how to implement open hardware initiatives. The program will provide guidelines on the allocation of funds, communication strategies, and integration with open science projects. We propose a national challenge on a specific topic that requires the use of open hardware. The challenge will serve as a platform for collaboration between academia, industry, and the public, and will showcase the potential of open hardware in addressing societal challenges.

**Collaboration Platform to write the paper:**
To facilitate collaboration and feedback, we propose the creation of a GitHub repository where the white paper and program document will be hosted. This platform will enable stakeholders to read, comment, and update the documents, and will also serve as a channel for communication and feedback.

**Timeline:**
We aim to complete the white paper within two months and submit it to NWO for consideration in their annual funding cycle. We plan to promote open hardware initiatives throughout the year, with the Open Science Festival as a major milestone. We will continue to collaborate with universities, industry partners, and the public to promote the benefits of open hardware and advocate for its implementation.

**Comment by SanliFaez** [comment]
some inspirations from the plan for NEWS center on science communciations
https://zenodo.org/record/7763918#.ZEI0IHZBzep

- using a block-diagram for explaining the content of the report: activities, output, impact
- why is NOHI important? why is it necessary? what can it do? how is this document helping?
- what is OH, what is OH good for? challenges of OH. societal need for OH
- target groups, stakeholders, beneficiaries
- some words on management and workload of NOHI

**Comment by jurra** [comment]
I am closing this one was we sorted it out
